//
// Created by 계용운 on 2023/05/21.
//

#ifndef INC_2023_HONGIK_SOFTWARE_ENGINEERING_LOGIN_H
#define INC_2023_HONGIK_SOFTWARE_ENGINEERING_LOGIN_H


class Login {

};


#endif //INC_2023_HONGIK_SOFTWARE_ENGINEERING_LOGIN_H
